-- public.iclock_transaction definition

-- Drop table

-- DROP TABLE public.iclock_transaction;

CREATE TABLE public.iclock_transaction (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	emp_code varchar(20) NOT NULL,
	punch_time timestamptz NOT NULL,
	punch_state varchar(5) NOT NULL,
	verify_type int4 NOT NULL,
	work_code varchar(20) NULL,
	terminal_sn varchar(50) NULL,
	terminal_alias varchar(50) NULL,
	area_alias varchar(100) NULL,
	longitude float8 NULL,
	latitude float8 NULL,
	gps_location text NULL,
	mobile varchar(50) NULL,
	"source" int2 NULL,
	purpose int2 NULL,
	crc varchar(100) NULL,
	is_attendance int2 NULL,
	reserved varchar(100) NULL,
	upload_time timestamptz NULL,
	sync_status int2 NULL,
	sync_time timestamptz NULL,
	is_mask int2 NULL,
	temperature numeric(4, 1) NULL,
	emp_id int4 NULL,
	terminal_id int4 NULL,
	company_code varchar(50) NULL,
	CONSTRAINT iclock_transaction_company_code_emp_code_pu_2665c3d7_uniq UNIQUE (company_code, emp_code, punch_time),
	CONSTRAINT iclock_transaction_pkey PRIMARY KEY (id)
);
CREATE INDEX iclock_transaction_emp_id_60fa3521 ON public.iclock_transaction USING btree (emp_id);
CREATE INDEX iclock_transaction_terminal_id_451c81c2 ON public.iclock_transaction USING btree (terminal_id);


-- public.iclock_transaction foreign keys

ALTER TABLE public.iclock_transaction ADD CONSTRAINT iclock_transaction_emp_id_60fa3521_fk_personnel_employee_id FOREIGN KEY (emp_id) REFERENCES public.personnel_employee(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.iclock_transaction ADD CONSTRAINT iclock_transaction_terminal_id_451c81c2_fk_iclock_terminal_id FOREIGN KEY (terminal_id) REFERENCES public.iclock_terminal(id) DEFERRABLE INITIALLY DEFERRED;


-- public.personnel_employee definition

-- Drop table

-- DROP TABLE public.personnel_employee;

CREATE TABLE public.personnel_employee (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamptz NULL,
	create_user varchar(150) NULL,
	change_time timestamptz NULL,
	change_user varchar(150) NULL,
	status int2 NOT NULL,
	emp_code varchar(20) NOT NULL,
	first_name varchar(100) NULL,
	last_name varchar(100) NULL,
	nickname varchar(100) NULL,
	passport varchar(30) NULL,
	driver_license_automobile varchar(30) NULL,
	driver_license_motorcycle varchar(30) NULL,
	photo varchar(200) NULL,
	self_password varchar(128) NULL,
	device_password varchar(20) NULL,
	dev_privilege int4 NULL,
	card_no varchar(20) NULL,
	acc_group varchar(5) NULL,
	acc_timezone varchar(20) NULL,
	gender varchar(1) NULL,
	birthday date NULL,
	address varchar(200) NULL,
	postcode varchar(10) NULL,
	office_tel varchar(20) NULL,
	contact_tel varchar(20) NULL,
	mobile varchar(20) NULL,
	"national" varchar(50) NULL,
	religion varchar(20) NULL,
	title varchar(20) NULL,
	enroll_sn varchar(20) NULL,
	ssn varchar(20) NULL,
	update_time timestamptz NULL,
	hire_date date NULL,
	verify_mode int4 NULL,
	city varchar(20) NULL,
	emp_type int2 NULL,
	enable_payroll bool NOT NULL,
	app_status int2 NULL,
	app_role int2 NULL,
	email varchar(50) NULL,
	last_login timestamptz NULL,
	is_active bool NOT NULL,
	session_key varchar(32) NULL,
	login_ip varchar(32) NULL,
	department_id int4 NULL,
	position_id int4 NULL,
	leave_group int4 NULL,
	emp_code_digit int8 NULL,
	superior_id int4 NULL,
	company_id int4 NOT NULL,
	CONSTRAINT personnel_employee_company_id_emp_code_81daa575_uniq UNIQUE (company_id, emp_code),
	CONSTRAINT personnel_employee_pkey PRIMARY KEY (id)
);
CREATE INDEX personnel_employee_company_id_95b3fd72 ON public.personnel_employee USING btree (company_id);
CREATE INDEX personnel_employee_department_id_068bbd08 ON public.personnel_employee USING btree (department_id);
CREATE INDEX personnel_employee_position_id_c9321343 ON public.personnel_employee USING btree (position_id);
CREATE INDEX personnel_employee_superior_id_ad6e1c47 ON public.personnel_employee USING btree (superior_id);


-- public.personnel_employee foreign keys

ALTER TABLE public.personnel_employee ADD CONSTRAINT personnel_employee_company_id_95b3fd72_fk_personnel_company_id FOREIGN KEY (company_id) REFERENCES public.personnel_company(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.personnel_employee ADD CONSTRAINT personnel_employee_department_id_068bbd08_fk_personnel FOREIGN KEY (department_id) REFERENCES public.personnel_department(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.personnel_employee ADD CONSTRAINT personnel_employee_position_id_c9321343_fk_personnel FOREIGN KEY (position_id) REFERENCES public.personnel_position(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.personnel_employee ADD CONSTRAINT personnel_employee_superior_id_ad6e1c47_fk_personnel FOREIGN KEY (superior_id) REFERENCES public.personnel_employee(id) DEFERRABLE INITIALLY DEFERRED;


-- public.personnel_employee definition

-- Drop table

-- DROP TABLE public.personnel_employee;

CREATE TABLE public.personnel_employee (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamptz NULL,
	create_user varchar(150) NULL,
	change_time timestamptz NULL,
	change_user varchar(150) NULL,
	status int2 NOT NULL,
	emp_code varchar(20) NOT NULL,
	first_name varchar(100) NULL,
	last_name varchar(100) NULL,
	nickname varchar(100) NULL,
	passport varchar(30) NULL,
	driver_license_automobile varchar(30) NULL,
	driver_license_motorcycle varchar(30) NULL,
	photo varchar(200) NULL,
	self_password varchar(128) NULL,
	device_password varchar(20) NULL,
	dev_privilege int4 NULL,
	card_no varchar(20) NULL,
	acc_group varchar(5) NULL,
	acc_timezone varchar(20) NULL,
	gender varchar(1) NULL,
	birthday date NULL,
	address varchar(200) NULL,
	postcode varchar(10) NULL,
	office_tel varchar(20) NULL,
	contact_tel varchar(20) NULL,
	mobile varchar(20) NULL,
	"national" varchar(50) NULL,
	religion varchar(20) NULL,
	title varchar(20) NULL,
	enroll_sn varchar(20) NULL,
	ssn varchar(20) NULL,
	update_time timestamptz NULL,
	hire_date date NULL,
	verify_mode int4 NULL,
	city varchar(20) NULL,
	emp_type int2 NULL,
	enable_payroll bool NOT NULL,
	app_status int2 NULL,
	app_role int2 NULL,
	email varchar(50) NULL,
	last_login timestamptz NULL,
	is_active bool NOT NULL,
	session_key varchar(32) NULL,
	login_ip varchar(32) NULL,
	department_id int4 NULL,
	position_id int4 NULL,
	leave_group int4 NULL,
	emp_code_digit int8 NULL,
	superior_id int4 NULL,
	company_id int4 NOT NULL,
	CONSTRAINT personnel_employee_company_id_emp_code_81daa575_uniq UNIQUE (company_id, emp_code),
	CONSTRAINT personnel_employee_pkey PRIMARY KEY (id)
);
CREATE INDEX personnel_employee_company_id_95b3fd72 ON public.personnel_employee USING btree (company_id);
CREATE INDEX personnel_employee_department_id_068bbd08 ON public.personnel_employee USING btree (department_id);
CREATE INDEX personnel_employee_position_id_c9321343 ON public.personnel_employee USING btree (position_id);
CREATE INDEX personnel_employee_superior_id_ad6e1c47 ON public.personnel_employee USING btree (superior_id);


-- public.personnel_employee foreign keys

ALTER TABLE public.personnel_employee ADD CONSTRAINT personnel_employee_company_id_95b3fd72_fk_personnel_company_id FOREIGN KEY (company_id) REFERENCES public.personnel_company(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.personnel_employee ADD CONSTRAINT personnel_employee_department_id_068bbd08_fk_personnel FOREIGN KEY (department_id) REFERENCES public.personnel_department(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.personnel_employee ADD CONSTRAINT personnel_employee_position_id_c9321343_fk_personnel FOREIGN KEY (position_id) REFERENCES public.personnel_position(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.personnel_employee ADD CONSTRAINT personnel_employee_superior_id_ad6e1c47_fk_personnel FOREIGN KEY (superior_id) REFERENCES public.personnel_employee(id) DEFERRABLE INITIALLY DEFERRED;

-- public.personnel_department definition

-- Drop table

-- DROP TABLE public.personnel_department;

CREATE TABLE public.personnel_department (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	dept_code varchar(50) NOT NULL,
	dept_name varchar(200) NOT NULL,
	is_default bool NOT NULL,
	parent_dept_id int4 NULL,
	dept_manager_id int4 NULL,
	company_id int4 NOT NULL,
	CONSTRAINT personnel_department_company_id_dept_code_dfa8fff7_uniq UNIQUE (company_id, dept_code),
	CONSTRAINT personnel_department_pkey PRIMARY KEY (id)
);
CREATE INDEX personnel_department_company_id_00867fd8 ON public.personnel_department USING btree (company_id);
CREATE INDEX personnel_department_dept_manager_id_c5124a7d ON public.personnel_department USING btree (dept_manager_id);
CREATE INDEX personnel_department_parent_dept_id_d0b44024 ON public.personnel_department USING btree (parent_dept_id);


-- public.personnel_department foreign keys

ALTER TABLE public.personnel_department ADD CONSTRAINT personnel_department_company_id_00867fd8_fk_personnel FOREIGN KEY (company_id) REFERENCES public.personnel_company(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.personnel_department ADD CONSTRAINT personnel_department_dept_manager_id_c5124a7d_fk_personnel FOREIGN KEY (dept_manager_id) REFERENCES public.personnel_employee(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.personnel_department ADD CONSTRAINT personnel_department_parent_dept_id_d0b44024_fk_personnel FOREIGN KEY (parent_dept_id) REFERENCES public.personnel_department(id) DEFERRABLE INITIALLY DEFERRED;


-- public.iclock_terminal definition

-- Drop table

-- DROP TABLE public.iclock_terminal;

CREATE TABLE public.iclock_terminal (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	create_time timestamptz NULL,
	create_user varchar(150) NULL,
	change_time timestamptz NULL,
	change_user varchar(150) NULL,
	status int2 NOT NULL,
	sn varchar(50) NOT NULL,
	alias varchar(50) NOT NULL,
	ip_address inet NOT NULL,
	real_ip inet NULL,
	state int4 NOT NULL,
	terminal_tz int2 NOT NULL,
	heartbeat int4 NOT NULL,
	transfer_mode int2 NOT NULL,
	transfer_interval int4 NOT NULL,
	transfer_time varchar(100) NOT NULL,
	product_type int2 NULL,
	is_attendance int2 NOT NULL,
	is_registration int2 NOT NULL,
	purpose int2 NULL,
	controller_type int2 NULL,
	authentication int2 NOT NULL,
	"style" varchar(20) NULL,
	upload_flag varchar(10) NULL,
	fw_ver varchar(100) NULL,
	push_protocol varchar(50) NOT NULL,
	push_ver varchar(50) NULL,
	"language" int4 NULL,
	is_tft bool NOT NULL,
	terminal_name varchar(30) NULL,
	platform varchar(30) NULL,
	oem_vendor varchar(50) NULL,
	log_stamp varchar(30) NULL,
	op_log_stamp varchar(30) NULL,
	capture_stamp varchar(30) NULL,
	user_count int4 NULL,
	transaction_count int4 NULL,
	fp_count int4 NULL,
	fp_alg_ver varchar(10) NULL,
	face_count int4 NULL,
	face_alg_ver varchar(10) NULL,
	fv_count int4 NULL,
	fv_alg_ver varchar(10) NULL,
	palm_count int4 NULL,
	palm_alg_ver varchar(10) NULL,
	lock_func int2 NOT NULL,
	last_activity timestamptz NULL,
	upload_time timestamptz NULL,
	push_time timestamptz NULL,
	is_access int2 NOT NULL,
	area_id int4 NULL,
	CONSTRAINT iclock_terminal_pkey PRIMARY KEY (id),
	CONSTRAINT iclock_terminal_sn_key UNIQUE (sn)
);
CREATE INDEX iclock_terminal_area_id_c019c6f0 ON public.iclock_terminal USING btree (area_id);
CREATE INDEX iclock_terminal_sn_209168b1_like ON public.iclock_terminal USING btree (sn varchar_pattern_ops);


-- public.iclock_terminal foreign keys

ALTER TABLE public.iclock_terminal ADD CONSTRAINT iclock_terminal_area_id_c019c6f0_fk_personnel_area_id FOREIGN KEY (area_id) REFERENCES public.personnel_area(id) DEFERRABLE INITIALLY DEFERRED;
